import { PERSISTENCE_DEFAULTS } from "../defaults.ts";

export const PERSISTENCE_HEARTBEAT_PATH = PERSISTENCE_DEFAULTS.heartbeatPath;
export const PERSISTENCE_HEARTBEAT_INTERVAL_MS =
	PERSISTENCE_DEFAULTS.heartbeatIntervalMs;
export const PERSISTENCE_HEARTBEAT_MAX_AGE_MS =
	PERSISTENCE_DEFAULTS.heartbeatMaxAgeMs;
export const PERSISTENCE_RECONCILE_INTERVAL_MS =
	PERSISTENCE_DEFAULTS.reconcileIntervalMs;
export const PERSISTENCE_EVENT_BATCH_WINDOW_MS =
	PERSISTENCE_DEFAULTS.eventBatchWindowMs;
