services:
  composery:
    build:
      context: .
      args:
        COMPOSERY_BUILD_REVISION: ${COMPOSERY_BUILD_REVISION:-unknown}
        COMPOSERY_BUILD_SOURCE: ${COMPOSERY_BUILD_SOURCE:-https://github.com/sloikodavid/composery}
        COMPOSERY_BUILD_VERSION: ${COMPOSERY_BUILD_VERSION:-unknown}
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - composery_data:/data

volumes:
  composery_data:
