// AUTO-GENERATED by packages/brand/scripts/sync.mjs - do not edit by hand.
// Source: packages/brand/index.mjs.
export const BRAND_NAME = "Composery";
export const LOGO_TEXT = "Composery";
export const ICON_VIEWBOX = "0 0 20 20";
export const ICON_CROP_VIEWBOX = "0 0 20 20";
export const ICON_XML =
	'<svg width="256" height="256" viewBox="0 0 20 20" fill="none" color="#000000" xmlns="http://www.w3.org/2000/svg"><g transform="translate(-0.7004597831639893 -0.7004597831639893) scale(1.1352670715785889) rotate(135 12 12)"><mask id="composery-icon-holes"><rect width="24" height="24" fill="#fff" stroke="none"/><circle cx="12" cy="15" r="3.6" fill="#000" stroke="none"/><path d="M12 15.5 L12 3.6" stroke="#000" stroke-linecap="round" stroke-width="2.1"/></mask><path d="M12 5 L17.6 14.6 C20.6 19.8 19.2 19.8 15.6 19.8 L8.4 19.8 C4.8 19.8 3.4 19.8 6.4 14.6 Z" fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.6" mask="url(#composery-icon-holes)"/></g></svg>';
export const BRAND_COLORS = {
	icon: {
		light: "#000000",
		dark: "#fafafa",
		muted: "#737373",
		tileStroke: "#ffffff"
	},
	surface: {
		ink: "#000000",
		paper: "#ffffff",
		canvas: "#fafafa",
		border: "#e5e5e5",
		lightText: "#000000",
		darkText: "#fafafa",
		tile: "#0a0a0a",
		splash: "#ffffff"
	},
	state: {
		success: "#16a34a",
		warning: "#dc8a06",
		destructive: "#dc2626",
		info: "#2563eb"
	}
} as const;
export const BRAND_THEME = {
	light: {
		background: "#ffffff",
		foreground: "#000000",
		card: "#ffffff",
		cardForeground: "#000000",
		popover: "#ffffff",
		popoverForeground: "#000000",
		primary: "#171717",
		primaryForeground: "#fafafa",
		secondary: "#f5f5f5",
		secondaryForeground: "#171717",
		muted: "#f5f5f5",
		mutedForeground: "#737373",
		accent: "#f5f5f5",
		accentForeground: "#171717",
		destructive: "#dc2626",
		success: "#16a34a",
		warning: "#dc8a06",
		border: "#e5e5e5",
		input: "#e5e5e5",
		ring: "#a3a3a3",
		overlay: "rgba(0, 0, 0, 0.4)",
		chart1: "#171717",
		chart2: "#525252",
		chart3: "#737373",
		chart4: "#a3a3a3",
		chart5: "#d4d4d4",
		sidebar: "#ffffff",
		sidebarForeground: "#000000",
		sidebarPrimary: "#171717",
		sidebarPrimaryForeground: "#fafafa",
		sidebarAccent: "#f5f5f5",
		sidebarAccentForeground: "#171717",
		sidebarBorder: "#e5e5e5",
		sidebarRing: "#a3a3a3"
	},
	dark: {
		background: "#0a0a0a",
		foreground: "#fafafa",
		card: "#0a0a0a",
		cardForeground: "#fafafa",
		popover: "#0a0a0a",
		popoverForeground: "#fafafa",
		primary: "#fafafa",
		primaryForeground: "#0a0a0a",
		secondary: "#171717",
		secondaryForeground: "#fafafa",
		muted: "#171717",
		mutedForeground: "#a3a3a3",
		accent: "#171717",
		accentForeground: "#fafafa",
		destructive: "#f87171",
		success: "#22c55e",
		warning: "#f5a80b",
		border: "#ffffff1f",
		input: "#ffffff29",
		ring: "#737373",
		overlay: "rgba(0, 0, 0, 0.4)",
		chart1: "#fafafa",
		chart2: "#d4d4d4",
		chart3: "#a3a3a3",
		chart4: "#737373",
		chart5: "#525252",
		sidebar: "#0a0a0a",
		sidebarForeground: "#fafafa",
		sidebarPrimary: "#fafafa",
		sidebarPrimaryForeground: "#0a0a0a",
		sidebarAccent: "#171717",
		sidebarAccentForeground: "#fafafa",
		sidebarBorder: "#ffffff1f",
		sidebarRing: "#737373"
	}
} as const;
