services:
  caddy:
    image: caddy:2.11.4-alpine@sha256:5f5c8640aae01df9654968d946d8f1a56c497f1dd5c5cda4cf95ab7c14d58648
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
    depends_on:
      composery:
        condition: service_started

  composery:
    image: ghcr.io/sloikodavid/composery:latest
    restart: unless-stopped
    env_file: ./composery.env
    volumes:
      - composery_data:/data
    expose:
      - "8080"

volumes:
  composery_data:
  caddy_data:
