import { spawn } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
	BRAND_NAME,
	ICON_CROP_VIEWBOX,
	ICON_HEIGHT,
	ICON_VIEWBOX,
	ICON_WIDTH,
	LOGO_TEXT,
	brandColors,
	iconInner,
	iconSvg,
	theme
} from "../packages/brand/index.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const generated = (source) =>
	`// AUTO-GENERATED by scripts/sync-brand.mjs - do not edit by hand.\n// Source: packages/brand/index.mjs.\n${source}`;

function json(value) {
	return JSON.stringify(value, null, "\t");
}

function cssVariableName(key) {
	return key
		.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)
		.replace(/([a-z])([0-9])/g, "$1-$2");
}

function cssThemeBlock(selector, values) {
	const lines = Object.entries(values).map(
		([key, value]) => `\t--${cssVariableName(key)}: ${value};`
	);
	return `${selector} {\n${lines.join("\n")}\n}`;
}

function webThemeCss() {
	return `/* AUTO-GENERATED by scripts/sync-brand.mjs - do not edit by hand.
   Source: packages/brand/index.mjs. */
${cssThemeBlock(":root", theme.light)}

${cssThemeBlock(".dark", theme.dark)}
`;
}

function idePageThemeCss() {
	const light = theme.light;
	const dark = theme.dark;

	return `/* AUTO-GENERATED by scripts/sync-brand.mjs - do not edit by hand.
   Source: packages/brand/index.mjs. */
:root {
	color-scheme: light dark;
	--vscode-button-background: ${light.primary};
	--vscode-button-foreground: ${light.primaryForeground};
	--vscode-button-hoverBackground: #404040;
	--vscode-editor-background: ${light.background};
	--vscode-errorForeground: ${light.destructive};
	--vscode-editorHoverWidget-background: ${light.popover};
	--vscode-editorHoverWidget-border: ${light.border};
	--vscode-editorHoverWidget-foreground: ${light.popoverForeground};
	--vscode-focusBorder: ${light.ring};
	--auth-input-focus: ${light.ring};
	--auth-message-background: ${light.muted};
	--auth-message-border: ${light.border};
	--vscode-foreground: ${light.foreground};
	--vscode-input-background: ${light.background};
	--vscode-input-border: #d4d4d4;
	--vscode-input-foreground: ${light.foreground};
	--vscode-cornerRadius-medium: 6px;
	--vscode-toolbar-activeBackground: #a6a6a650;
	--vscode-toolbar-hoverBackground: #b8b8b850;
	--vscode-toolbar-hoverOutline: transparent;
	--vscode-shadow-hover: 0 2px 8px #00000026;
}

@media (prefers-color-scheme: dark) {
	:root {
		--vscode-button-background: ${dark.primary};
		--vscode-button-foreground: ${dark.primaryForeground};
		--vscode-button-hoverBackground: #e5e5e5;
		--vscode-focusBorder: ${dark.ring};
		--vscode-editor-background: ${dark.background};
		--vscode-editorHoverWidget-background: ${dark.secondary};
		--vscode-editorHoverWidget-border: ${dark.border};
		--vscode-editorHoverWidget-foreground: ${dark.popoverForeground};
		--vscode-errorForeground: ${dark.destructive};
		--auth-input-focus: ${dark.ring};
		--auth-message-background: ${dark.secondary};
		--auth-message-border: ${dark.border};
		--vscode-foreground: ${dark.foreground};
		--vscode-input-background: ${dark.secondary};
		--vscode-input-border: ${dark.input};
		--vscode-input-foreground: ${dark.foreground};
		--vscode-toolbar-activeBackground: #6c6f7050;
		--vscode-toolbar-hoverBackground: #5a5d5e50;
		--vscode-shadow-hover: 0 2px 8px #0000005c;
	}
}
`;
}

function applyIdeColorRoles(colors, scheme) {
	const light = scheme === "light";
	const active = light ? theme.light : theme.dark;
	const subtle = light ? "#00000014" : "#ffffff1f";
	const softer = light ? "#0000000f" : "#ffffff14";
	const strong = light ? "#00000026" : "#ffffff26";
	const ruler = light ? "#00000033" : "#ffffff33";
	const hover = active.muted;
	const muted = active.mutedForeground;
	const bg = active.background;
	const fg = active.foreground;
	const border = active.border;
	const primary = active.primary;
	const primaryForeground = active.primaryForeground;
	const link = light ? active.foreground : "#d4d4d4";

	Object.assign(colors, {
		"activityBar.activeBorder": primary,
		"activityBar.background": bg,
		"activityBar.border": border,
		"activityBar.foreground": fg,
		"activityBar.inactiveForeground": muted,
		"activityBarBadge.background": primary,
		"activityBarBadge.foreground": primaryForeground,
		"badge.background": hover,
		"badge.foreground": fg,
		"button.background": primary,
		"button.foreground": primaryForeground,
		"button.hoverBackground": light ? "#404040" : "#e5e5e5",
		"button.secondaryBackground": hover,
		"button.secondaryForeground": fg,
		"button.secondaryHoverBackground": light ? "#fafafa" : "#262626",
		"chat.slashCommandBackground": strong,
		"chat.slashCommandForeground": fg,
		"checkbox.background": hover,
		"checkbox.border": border,
		"dropdown.background": hover,
		"dropdown.border": border,
		"editor.background": bg,
		"editor.findMatchBackground": strong,
		"editor.foreground": fg,
		"editor.inactiveSelectionBackground": hover,
		"editor.selectionBackground": light ? "#0000001f" : "#262626",
		"editor.selectionHighlightBackground": softer,
		"editor.wordHighlightBackground": softer,
		"editor.wordHighlightStrongBackground": strong,
		"editor.findMatchHighlightBackground": strong,
		"editor.foldBackground": strong,
		"editor.hoverHighlightBackground": strong,
		"editorHoverWidget.highlightForeground": strong,
		"editorGroup.border": border,
		"editorGroupHeader.tabsBackground": bg,
		"editorGroupHeader.tabsBorder": border,
		"editorGutter.modifiedBackground": link,
		"editorLineNumber.activeForeground": fg,
		"editorOverviewRuler.border": light ? "#0000001f" : "#ffffff12",
		"editorOverviewRuler.findMatchForeground": ruler,
		"editorOverviewRuler.infoForeground": muted,
		"editorOverviewRuler.selectionHighlightForeground": ruler,
		"editorWidget.background": bg,
		"editorWidget.border": border,
		"editorHoverWidget.background": bg,
		"editorHoverWidget.border": border,
		"editorSuggestWidget.background": bg,
		"editorSuggestWidget.border": border,
		"editorSuggestWidget.selectedBackground": hover,
		"editorSuggestWidget.highlightForeground": link,
		"editorSuggestWidget.focusHighlightForeground": link,
		focusBorder: primary,
		"input.background": light ? "#ffffff" : bg,
		"input.border": border,
		"inputOption.activeBackground": subtle,
		"inputOption.activeBorder": primary,
		"inputOption.activeForeground": fg,
		"list.activeSelectionBackground": hover,
		"list.activeSelectionForeground": fg,
		"list.focusAndSelectionOutline": primary,
		"list.focusHighlightForeground": link,
		"list.focusOutline": primary,
		"list.highlightForeground": link,
		"list.hoverBackground": hover,
		"list.inactiveSelectionBackground": hover,
		"list.dropBackground": subtle,
		"menu.background": bg,
		"menu.border": border,
		"menu.selectionBackground": subtle,
		"menu.selectionForeground": fg,
		"notificationCenterHeader.background": bg,
		"notifications.background": bg,
		"notifications.border": border,
		"notebook.selectedCellBackground": strong,
		"panel.background": bg,
		"panel.border": border,
		"panelSectionHeader.background": bg,
		"panelTitle.activeBorder": primary,
		"peekView.border": primary,
		"peekViewEditor.background": bg,
		"peekViewEditor.matchHighlightBackground": strong,
		"peekViewResult.background": bg,
		"peekViewResult.matchHighlightBackground": strong,
		"peekViewResult.selectionBackground": hover,
		"peekViewTitle.background": bg,
		"pickerGroup.border": border,
		"pickerGroup.foreground": link,
		"progressBar.background": primary,
		"quickInput.background": bg,
		"quickInputList.focusBackground": hover,
		"settings.focusedRowBorder": strong,
		"settings.headerForeground": fg,
		"settings.modifiedItemIndicator": primary,
		"sideBar.background": bg,
		"sideBar.border": border,
		"sideBarSectionHeader.background": bg,
		"sideBarSectionHeader.border": border,
		"sideBarTitle.foreground": muted,
		"statusBar.background": bg,
		"statusBar.border": border,
		"statusBar.debuggingBackground": primary,
		"statusBar.debuggingForeground": primaryForeground,
		"statusBar.focusBorder": primary,
		"statusBar.foreground": muted,
		"statusBar.noFolderBackground": bg,
		"statusBarItem.focusBorder": primary,
		"statusBarItem.remoteBackground": primary,
		"statusBarItem.remoteForeground": primaryForeground,
		"scrollbarSlider.background": light ? "#0a0a0a1f" : "#ffffff17",
		"scrollbarSlider.hoverBackground": light ? "#0a0a0a2e" : "#ffffff26",
		"scrollbarSlider.activeBackground": light ? "#0a0a0a40" : "#ffffff33",
		"tab.activeBackground": bg,
		"tab.activeBorder": bg,
		"tab.activeBorderTop": primary,
		"tab.activeForeground": fg,
		"tab.border": border,
		"tab.hoverBackground": hover,
		"tab.inactiveBackground": bg,
		"tab.inactiveForeground": muted,
		"tab.selectedBorderTop": primary,
		"tab.unfocusedActiveModifiedBorder": light ? "#0a0a0a40" : "#ffffff40",
		"terminal.background": bg,
		"terminal.inactiveSelectionBackground": subtle,
		"terminal.tab.activeBorder": primary,
		"terminalCursor.foreground": link,
		"terminalCommandDecoration.successBackground": subtle,
		"textLink.activeForeground": link,
		"textLink.foreground": link,
		"textPreformat.foreground": link,
		"titleBar.activeBackground": bg,
		"titleBar.activeForeground": fg,
		"titleBar.border": border,
		"titleBar.inactiveBackground": bg,
		"welcomePage.progress.background": light ? "#0a0a0a1f" : "#ffffff17",
		"welcomePage.tileBackground": hover,
		"widget.border": border,
		"agentsUpdateButton.downloadingBackground": strong,
		"agentsUpdateButton.downloadedBackground": light ? "#0a0a0a40" : "#ffffff40"
	});
}

async function syncIdeTheme(name, scheme) {
	const path = join(
		root,
		"packages",
		"ide",
		"overlay",
		"lib",
		"vscode",
		"extensions",
		"composery-themes",
		"themes",
		`${name}.json`
	);
	const themeJson = JSON.parse(await readFile(path, "utf8"));
	themeJson["//"] =
		`${themeJson.name}, the default ${scheme} theme (see ThemeSettingDefaults in workbenchThemeService.ts). Neutral retint of VS Code ${scheme === "dark" ? "Dark" : "Light"} Modern using the shared brand palette. Syntax (tokenColors) stays Modern for readability.`;
	applyIdeColorRoles(themeJson.colors, scheme);
	await writeFile(path, `${json(themeJson)}\n`);
	return themeJson;
}

function replaceTsObject(source, objectName, colors) {
	const entries = Object.entries(colors)
		.map(([key, value]) => `\t'${key}': '${value}'`)
		.join(",\n");
	const replacement = `export const ${objectName} = {\n${entries}\n};`;
	const pattern = new RegExp(
		`export const ${objectName} = \\{[\\s\\S]*?\\n\\};`
	);
	return source.replace(pattern, replacement);
}

function gitDiff(basePath, modifiedPath, label) {
	return new Promise((resolve, reject) => {
		const child = spawn(
			"git",
			["diff", "--no-index", "--no-ext-diff", "--text", basePath, modifiedPath],
			{ cwd: root }
		);
		let stdout = "";
		let stderr = "";
		child.stdout.on("data", (chunk) => {
			stdout += chunk;
		});
		child.stderr.on("data", (chunk) => {
			stderr += chunk;
		});
		child.on("error", reject);
		child.on("close", (code) => {
			if (code === 0 || code === 1) {
				const body = stdout
					.split(/\r?\n/)
					.filter(
						(line) =>
							!line.startsWith("diff --git ") &&
							!line.startsWith("index ") &&
							!line.startsWith("--- ") &&
							!line.startsWith("+++ ")
					)
					.join("\n");
				resolve(
					`diff --git a/${label} b/${label}\n--- a/${label}\n+++ b/${label}\n${body}`
				);
				return;
			}
			reject(new Error(stderr || `git diff exited with ${code}`));
		});
	});
}

async function syncDefaultColorThemePatch({ darkTheme, lightTheme }) {
	const label =
		"lib/vscode/src/vs/workbench/services/themes/common/workbenchThemeService.ts";
	const upstream = join(root, "packages", "ide", "upstream", label);
	let modified = await readFile(upstream, "utf8");
	modified = modified
		.replace(
			"export const COLOR_THEME_DARK = 'Dark 2026';",
			"export const COLOR_THEME_DARK = 'Composery Dark';"
		)
		.replace(
			"export const COLOR_THEME_LIGHT = 'Light 2026';",
			"export const COLOR_THEME_LIGHT = 'Composery Light';"
		);
	modified = replaceTsObject(
		modified,
		"COLOR_THEME_DARK_INITIAL_COLORS",
		darkTheme.colors
	);
	modified = replaceTsObject(
		modified,
		"COLOR_THEME_LIGHT_INITIAL_COLORS",
		lightTheme.colors
	);

	const dir = await mkdtemp(join(tmpdir(), "composery-brand-"));
	try {
		const basePath = join(dir, "base.ts");
		const modifiedPath = join(dir, "modified.ts");
		await writeFile(basePath, await readFile(upstream, "utf8"));
		await writeFile(modifiedPath, modified);
		await writeFile(
			join(root, "packages", "ide", "patches", "default-color-theme.diff"),
			await gitDiff(basePath, modifiedPath, label)
		);
	} finally {
		await rm(dir, { recursive: true, force: true });
	}
}

await writeFile(
	join(root, "packages", "web", "lib", "brand.ts"),
	generated(
		`export const BRAND_NAME = ${json(BRAND_NAME)};\nexport const LOGO_TEXT = ${json(LOGO_TEXT)};\nexport const ICON_VIEWBOX = ${json(ICON_VIEWBOX)};\nexport const ICON_WIDTH = ${ICON_WIDTH};\nexport const ICON_HEIGHT = ${ICON_HEIGHT};\nexport const ICON_SVG = ${json(iconInner())};\nexport const BRAND_COLORS = ${json(brandColors)} as const;\nexport const BRAND_THEME = ${json(theme)} as const;\n`
	)
);

await writeFile(
	join(root, "packages", "mobile", "src", "lib", "brand.ts"),
	generated(
		`export const BRAND_NAME = ${json(BRAND_NAME)};\nexport const LOGO_TEXT = ${json(LOGO_TEXT)};\nexport const ICON_VIEWBOX = ${json(ICON_VIEWBOX)};\nexport const ICON_CROP_VIEWBOX = ${json(ICON_CROP_VIEWBOX)};\nexport const ICON_XML = ${json(iconSvg({ viewBox: ICON_CROP_VIEWBOX }))};\nexport const BRAND_COLORS = ${json(brandColors)} as const;\nexport const BRAND_THEME = ${json(theme)} as const;\n`
	)
);

await writeFile(
	join(root, "packages", "web", "app", "brand.css"),
	webThemeCss()
);
await writeFile(
	join(
		root,
		"packages",
		"ide",
		"overlay",
		"src",
		"browser",
		"pages",
		"brand.css"
	),
	idePageThemeCss()
);

await writeFile(
	join(root, "packages", "web", "app", "icon.svg"),
	`${iconSvg()}\n`
);

const favicon = `${iconSvg({ height: "100%", width: "100%" })}\n`;
await writeFile(
	join(
		root,
		"packages",
		"ide",
		"overlay",
		"src",
		"browser",
		"media",
		"favicon.svg"
	),
	favicon
);
await writeFile(
	join(
		root,
		"packages",
		"ide",
		"overlay",
		"src",
		"browser",
		"media",
		"favicon-dark-support.svg"
	),
	favicon
);

const appJsonPath = join(root, "packages", "mobile", "app.json");
const appJson = JSON.parse(await readFile(appJsonPath, "utf8"));
appJson.expo.android.adaptiveIcon.backgroundColor = brandColors.surface.tile;
const splash = appJson.expo.plugins.find(
	(plugin) => Array.isArray(plugin) && plugin[0] === "expo-splash-screen"
);
if (splash) splash[1].backgroundColor = brandColors.surface.splash;
await writeFile(appJsonPath, `${json(appJson)}\n`);

const darkTheme = await syncIdeTheme("composery-dark", "dark");
const lightTheme = await syncIdeTheme("composery-light", "light");
await syncDefaultColorThemePatch({ darkTheme, lightTheme });

console.log(
	"Synced generated brand adapters, CSS, IDE theme data, and static SVGs."
);
