import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import {
	ICON_VIEWBOX,
	brandColors,
	iconInner,
	iconSvg,
	theme
} from "../index.ts";
import { formatContent } from "../../../scripts/write-formatted.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const webApp = join(root, "packages", "web", "app");
const webPublic = join(root, "packages", "web", "public");
const ideBrowser = join(root, "packages", "ide", "overlay", "src", "browser");
const ideMedia = join(ideBrowser, "media");

// `--check` verifies committed text assets and unavoidable literal copies still
// match theme.json through the generated theme export.
// guard, wired into `pnpm check`) instead of writing. Every output of this script
// is deterministic from index.ts, so the check covers all of them; the font- and
// sharp-derived assets (logo.mjs, icons.mjs) stay outside this script.
const CHECK = process.argv.includes("--check");
const stale = [];

async function emit(path, content) {
	const formatted = await formatContent(path, content);
	if (!CHECK) {
		await writeFile(path, formatted);
		return;
	}
	const current = await readFile(path, "utf8").catch(() => null);
	if (current !== formatted) stale.push(relative(root, path));
}

function json(value) {
	return JSON.stringify(value, null, "\t");
}

function cssVariableName(key) {
	return key
		.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)
		.replace(/([a-z])([0-9])/g, "$1-$2");
}

function cssThemeBlock(selector, values) {
	const lines = Object.entries(values).map(
		([key, value]) => `\t--${cssVariableName(key)}: ${value};`
	);
	return `${selector} {\n${lines.join("\n")}\n}`;
}

function webThemeCss() {
	return `/* AUTO-GENERATED by packages/shared/scripts/sync.mjs - do not edit by hand.
   Source: packages/shared/theme.json. */
${cssThemeBlock(":root", theme.light)}

${cssThemeBlock(".dark", theme.dark)}
`;
}

// Per-scheme variables for the auth/error pages, serialized once per scheme so
// the media-query blocks (browsers) and the [data-scheme] blocks (the mobile
// app stamps its scheme there - an Android WebView's native prefers-color-scheme
// tracks the activity theme, not the system) can never drift apart.
function idePageSchemeVars(c, dark) {
	return {
		"--vscode-button-background": c.primary,
		"--vscode-button-foreground": c.primaryForeground,
		"--vscode-button-hoverBackground": dark ? c.foreground : c.mutedForeground,
		"--vscode-focusBorder": c.ring,
		"--vscode-editor-background": c.background,
		"--vscode-editorHoverWidget-background": dark ? c.secondary : c.popover,
		"--vscode-editorHoverWidget-border": c.border,
		"--vscode-editorHoverWidget-foreground": c.popoverForeground,
		"--vscode-errorForeground": c.destructive,
		"--vscode-descriptionForeground": c.mutedForeground,
		"--auth-success": c.success,
		"--auth-warning": c.warning,
		"--auth-input-focus": c.ring,
		"--vscode-foreground": c.foreground,
		"--vscode-input-background": dark ? c.secondary : c.background,
		"--vscode-input-border": dark ? c.input : c.secondary,
		"--vscode-input-foreground": c.foreground,
		"--vscode-toolbar-activeBackground": `${c.mutedForeground}50`,
		"--vscode-toolbar-hoverBackground": `${c.muted}80`,
		"--vscode-shadow-hover": dark
			? "0 2px 8px #0000005c"
			: "0 2px 8px #00000026"
	};
}

function idePageThemeCss() {
	const cssVars = (vars, indent) =>
		Object.entries(vars)
			.map(([k, v]) => `${indent}${k}: ${v};`)
			.join("\n");
	const lightVars = idePageSchemeVars(theme.light, false);
	const darkVars = idePageSchemeVars(theme.dark, true);

	return `/* AUTO-GENERATED by packages/shared/scripts/sync.mjs - do not edit by hand.
   Source: packages/shared/theme.json. */
:root {
	color-scheme: light dark;
${cssVars(lightVars, "\t")}
	--vscode-cornerRadius-medium: 6px;
	--vscode-toolbar-hoverOutline: transparent;
}

@media (prefers-color-scheme: dark) {
	:root {
${cssVars(darkVars, "\t\t")}
	}
}

/* App override: the mobile app stamps data-scheme with the app scheme. */
:root[data-scheme="light"] {
${cssVars(lightVars, "\t")}
}

:root[data-scheme="dark"] {
${cssVars(darkVars, "\t")}
}
`;
}

// Browser favicon that follows the colour scheme (like github.com and
// polar.sh): a dark mark on a light UI, a light mark on a dark UI. It takes two
// kinds of file, because neither can do both jobs.
//
// The adaptive one carries its own prefers-color-scheme rule, so it is right on
// first paint and with JS off; this is the file pages declare. The scheme-pinned
// pair is one fixed colour each: Chromium rasterizes a favicon once per URL and
// never re-runs the embedded media query, so the adaptive file alone only ever
// changes across a reload. The favicon scripts point the link at a pinned file
// instead, and a new URL is something every browser does re-render.
//
// Pages must declare the .ico fallback FIRST with an explicit sizes attribute
// and the adaptive SVG LAST with sizes="any" - Chromium picks an unsized (or
// later-listed) ICO over the SVG and the tab icon stops following the colour
// scheme.
const adaptiveFavicon = ({ width = 256, height = 256 } = {}) =>
	`<svg width="${width}" height="${height}" viewBox="${ICON_VIEWBOX}" fill="none" xmlns="http://www.w3.org/2000/svg"><style>svg{color:${brandColors.icon.light}}@media (prefers-color-scheme:dark){svg{color:${brandColors.icon.dark}}}</style>${iconInner()}</svg>`;

const pinnedFavicon = ({ scheme, width = 256, height = 256 }) =>
	iconSvg({ color: brandColors.icon[scheme], height, width });

await emit(join(webApp, "brand.css"), webThemeCss());

await emit(join(ideBrowser, "pages", "brand.css"), idePageThemeCss());

function replaceOne(source, pattern, replacement, name) {
	const matches = source.match(new RegExp(pattern.source, "g")) ?? [];
	if (matches.length !== 1)
		throw new Error(
			`${name}: expected one palette literal, found ${matches.length}`
		);
	return source.replace(pattern, replacement);
}

const readinessPath = join(
	root,
	"packages",
	"ide",
	"overlay",
	"src",
	"node",
	"persistence",
	"readiness.ts"
);
let readiness = await readFile(readinessPath, "utf8");
for (const [name, pattern, replacement] of [
	[
		"startup light",
		/(body\{margin:0;background:)#[0-9a-f]{6}(;color:)#[0-9a-f]{6}/i,
		`$1${theme.light.background}$2${theme.light.foreground}`
	],
	[
		"startup dark",
		/(@media \(prefers-color-scheme:dark\)\{body\{background:)#[0-9a-f]{6}(;color:)#[0-9a-f]{6}/i,
		`$1${theme.dark.background}$2${theme.dark.foreground}`
	],
	[
		"startup app light",
		/(html\[data-scheme="light"\] body\{background:)#[0-9a-f]{6}(;color:)#[0-9a-f]{6}/i,
		`$1${theme.light.background}$2${theme.light.foreground}`
	],
	[
		"startup app dark",
		/(html\[data-scheme="dark"\] body\{background:)#[0-9a-f]{6}(;color:)#[0-9a-f]{6}/i,
		`$1${theme.dark.background}$2${theme.dark.foreground}`
	]
])
	readiness = replaceOne(readiness, pattern, replacement, name);
await emit(readinessPath, readiness);

const androidDialogPath = join(
	root,
	"packages",
	"mobile",
	"plugins",
	"android-dialog-theme.js"
);
const androidDialog = replaceOne(
	await readFile(androidDialogPath, "utf8"),
	/const ACCENT = \{ light: "#[0-9a-f]{6}", dark: "#[0-9a-f]{6}" \};/i,
	`const ACCENT = { light: "${theme.light.primary}", dark: "${theme.dark.primary}" };`,
	"Android dialog accent"
);
await emit(androidDialogPath, androidDialog);

await emit(join(webApp, "icon.svg"), `${adaptiveFavicon()}\n`);
await emit(
	join(webPublic, "icon-light.svg"),
	`${pinnedFavicon({ scheme: "light" })}\n`
);
await emit(
	join(webPublic, "icon-dark.svg"),
	`${pinnedFavicon({ scheme: "dark" })}\n`
);

// The editor's favicons size themselves off the <link>, not a fixed box.
const ideFaviconBox = { width: "100%", height: "100%" };
await emit(
	join(ideMedia, "favicon.svg"),
	`${adaptiveFavicon(ideFaviconBox)}\n`
);
await emit(
	join(ideMedia, "favicon-light.svg"),
	`${pinnedFavicon({ scheme: "light", ...ideFaviconBox })}\n`
);
await emit(
	join(ideMedia, "favicon-dark.svg"),
	`${pinnedFavicon({ scheme: "dark", ...ideFaviconBox })}\n`
);

const appJson = JSON.parse(
	await readFile(join(root, "packages", "mobile", "app.json"), "utf8")
);
appJson.expo.android.adaptiveIcon.backgroundColor = brandColors.surface.tile;
const splash = appJson.expo.plugins.find(
	(plugin) => Array.isArray(plugin) && plugin[0] === "expo-splash-screen"
);
if (splash) {
	splash[1].backgroundColor = brandColors.surface.splash;
	splash[1].dark.backgroundColor = brandColors.surface.splashDark;
}
await emit(join(root, "packages", "mobile", "app.json"), `${json(appJson)}\n`);

if (CHECK) {
	if (stale.length) {
		console.error(
			`Brand assets are stale - run \`pnpm assets\`:\n${stale
				.map((path) => `  ${path}`)
				.join("\n")}`
		);
		process.exit(1);
	}
	console.log("Brand assets are up to date.");
} else {
	console.log("Synced generated brand CSS and SVGs.");
}
