import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { ICON_VIEWBOX, brandColors, iconInner, theme } from "../index.ts";
import { formatContent } from "../../../scripts/write-formatted.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");

// `--check` verifies the committed CSS/SVG assets still match index.ts (drift
// guard, wired into `pnpm check`) instead of writing. Every output of this script
// is deterministic from index.ts, so the check covers all of them; the font- and
// sharp-derived assets (logo.mjs, icons.mjs) are not hermetic and stay outside
// this script. The IDE color themes are hand-authored files, not generated -
// tests/code-server-patches.test.ts guards their overlap with the brand palette.
const CHECK = process.argv.includes("--check");
const stale = [];

async function emit(path, content) {
	const formatted = await formatContent(path, content);
	if (!CHECK) {
		await writeFile(path, formatted);
		return;
	}
	const current = await readFile(path, "utf8").catch(() => null);
	if (current !== formatted) stale.push(relative(root, path));
}

function json(value) {
	return JSON.stringify(value, null, "\t");
}

function cssVariableName(key) {
	return key
		.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)
		.replace(/([a-z])([0-9])/g, "$1-$2");
}

function cssThemeBlock(selector, values) {
	const lines = Object.entries(values).map(
		([key, value]) => `\t--${cssVariableName(key)}: ${value};`
	);
	return `${selector} {\n${lines.join("\n")}\n}`;
}

function webThemeCss() {
	return `/* AUTO-GENERATED by packages/shared/scripts/sync.mjs - do not edit by hand.
   Source: packages/shared/index.ts. */
${cssThemeBlock(":root", theme.light)}

${cssThemeBlock(".dark", theme.dark)}
`;
}

// Per-scheme variables for the auth/error pages, serialized once per scheme so
// the media-query blocks (browsers) and the [data-scheme] blocks (the mobile
// app stamps its scheme there - an Android WebView's native prefers-color-scheme
// tracks the activity theme, not the system) can never drift apart.
function idePageSchemeVars(c, dark) {
	return {
		"--vscode-button-background": c.primary,
		"--vscode-button-foreground": c.primaryForeground,
		"--vscode-button-hoverBackground": dark ? "#e5e5e5" : "#404040",
		"--vscode-focusBorder": c.ring,
		"--vscode-editor-background": c.background,
		"--vscode-editorHoverWidget-background": dark ? c.secondary : c.popover,
		"--vscode-editorHoverWidget-border": c.border,
		"--vscode-editorHoverWidget-foreground": c.popoverForeground,
		"--vscode-errorForeground": c.destructive,
		"--vscode-descriptionForeground": c.mutedForeground,
		"--auth-success": c.success,
		"--auth-warning": c.warning,
		"--auth-input-focus": c.ring,
		"--vscode-foreground": c.foreground,
		"--vscode-input-background": dark ? c.secondary : c.background,
		"--vscode-input-border": dark ? c.input : "#d4d4d4",
		"--vscode-input-foreground": c.foreground,
		"--vscode-toolbar-activeBackground": dark ? "#6c6f7050" : "#a6a6a650",
		"--vscode-toolbar-hoverBackground": dark ? "#5a5d5e50" : "#b8b8b850",
		"--vscode-shadow-hover": dark
			? "0 2px 8px #0000005c"
			: "0 2px 8px #00000026"
	};
}

function idePageThemeCss() {
	const cssVars = (vars, indent) =>
		Object.entries(vars)
			.map(([k, v]) => `${indent}${k}: ${v};`)
			.join("\n");
	const lightVars = idePageSchemeVars(theme.light, false);
	const darkVars = idePageSchemeVars(theme.dark, true);

	return `/* AUTO-GENERATED by packages/shared/scripts/sync.mjs - do not edit by hand.
   Source: packages/shared/index.ts. */
:root {
	color-scheme: light dark;
${cssVars(lightVars, "\t")}
	--vscode-cornerRadius-medium: 6px;
	--vscode-toolbar-hoverOutline: transparent;
}

@media (prefers-color-scheme: dark) {
	:root {
${cssVars(darkVars, "\t\t")}
	}
}

/* App override: the mobile app stamps data-scheme with the app scheme. */
:root[data-scheme="light"] {
${cssVars(lightVars, "\t")}
}

:root[data-scheme="dark"] {
${cssVars(darkVars, "\t")}
}
`;
}

// Browser favicon that follows the OS/browser colour scheme (like github.com
// and polar.sh): a dark mark on a light UI, a light mark on a dark UI.
// Pages must declare the .ico fallback FIRST with an explicit sizes attribute
// and this SVG LAST with sizes="any" - Chromium picks an unsized (or
// later-listed) ICO over the SVG and the tab icon stops following the colour
// scheme.
const adaptiveFavicon = ({ width = 256, height = 256 } = {}) =>
	`<svg width="${width}" height="${height}" viewBox="${ICON_VIEWBOX}" fill="none" xmlns="http://www.w3.org/2000/svg"><style>svg{color:${brandColors.icon.light}}@media (prefers-color-scheme:dark){svg{color:${brandColors.icon.dark}}}</style>${iconInner()}</svg>`;

await emit(join(root, "packages", "web", "app", "brand.css"), webThemeCss());

await emit(
	join(
		root,
		"packages",
		"ide",
		"overlay",
		"src",
		"browser",
		"pages",
		"brand.css"
	),
	idePageThemeCss()
);

await emit(
	join(root, "packages", "web", "app", "icon.svg"),
	`${adaptiveFavicon()}\n`
);

await emit(
	join(
		root,
		"packages",
		"ide",
		"overlay",
		"src",
		"browser",
		"media",
		"favicon.svg"
	),
	`${adaptiveFavicon({ width: "100%", height: "100%" })}\n`
);

const appJson = JSON.parse(
	await readFile(join(root, "packages", "mobile", "app.json"), "utf8")
);
appJson.expo.android.adaptiveIcon.backgroundColor = brandColors.surface.tile;
const splash = appJson.expo.plugins.find(
	(plugin) => Array.isArray(plugin) && plugin[0] === "expo-splash-screen"
);
if (splash) splash[1].backgroundColor = brandColors.surface.splash;
await emit(join(root, "packages", "mobile", "app.json"), `${json(appJson)}\n`);

if (CHECK) {
	if (stale.length) {
		console.error(
			`Brand assets are stale - run \`pnpm assets\`:\n${stale
				.map((path) => `  ${path}`)
				.join("\n")}`
		);
		process.exit(1);
	}
	console.log("Brand assets are up to date.");
} else {
	console.log("Synced generated brand CSS and SVGs.");
}
