import type { Doc } from "./_generated/dataModel";
import type { MutationCtx } from "./_generated/server";
import { boxPath } from "../lib/boxes/route";
import { SUPPORT_EMAIL } from "../lib/links";
import { optionalWebsiteUrl } from "./env";
import { appendBoxEvent } from "./boxes/events";
import { ownerSender, resendClient } from "./email";
import { raiseAlert } from "./staff/alerts";
import { findUserByClerkId } from "./users";
import type { OperationTrigger } from "./schema";
import { HOUR_MS } from "./time";

// What a box owner is told by email, and when.
//
// Four notices, not a feed. Each one is a fact about the owner's own box that
// they cannot learn any other way at the moment it becomes true: nobody opens
// the website to check whether the box they were not using is still there. Every
// other thing a box does - started, stopped, snapshotted, an update waiting - is
// already on its page for whoever goes looking, and mailing those would train an
// owner to ignore the four that matter.
//
// The boundary with the other two senders is absolute, because two systems
// mailing about the same event is how a customer ends up believing the wrong
// one: Polar owns every billing email (receipt, renewal, failed charge, dunning,
// cancellation) and Clerk owns every identity email. Nothing here restates
// either. `docs/developing/web/services/resend.md` is the canonical statement of
// that split.

// Composery's own free text is forwarded; a person's is not.
//
// An automatic suspension's reason is generated by `boxes/metrics.ts` from a
// threshold the owner is measured against, so it is both factual and safe to
// repeat. A staff suspension's reason is a free-text note written into the
// console for other staff - "chargeback pending", "suspected card fraud, do not
// warn" - and forwarding it would publish an internal note to its subject. So
// the rule is the sender, not the wording, and there is no per-message judgement
// call to get wrong later.
const AUTOMATIC_SUSPENSION: OperationTrigger = "system:abuse_suspension";

// One alert per window however many owners could not be reached. A queue failure
// is a property of the deployment (key revoked, sender unverified, component
// down), never of one owner, so per-box alerts would be the same incident
// repeated once per box in the fleet.
const OWNER_EMAIL_ALERT_WINDOW_MS = 6 * HOUR_MS;

export type OwnerNotice =
	| { type: "deleted"; trigger: OperationTrigger | undefined }
	| {
			type: "suspended";
			trigger: OperationTrigger | undefined;
			reason: string | undefined;
	  }
	| { type: "unsuspended" }
	| { type: "create_failed" };

// Why a box was deleted, in the owner's terms.
//
// Read off the operation's trigger because that is the only record of who
// ordered the teardown that survives into the mutation that finishes it. A
// trigger with no sentence here contributes none: `system:delete_retry` finishes
// a deletion some earlier operation ordered, so its own row genuinely does not
// know the reason, and inventing a plausible one would be worse than the
// deletion notice standing on its own.
function deletionReason(trigger: OperationTrigger | undefined) {
	if (trigger === "system:subscription_revoked") {
		return "Its subscription ended. A box exists only while its subscription is active.";
	}
	if (trigger === "system:account_deletion") {
		return "You asked us to delete your Composery account, and every box on the account goes with it.";
	}
	if (trigger === "staff") return "Composery staff deleted it.";
	return undefined;
}

function paragraphs(lines: (string | undefined)[]) {
	return lines.filter((line) => line !== undefined).join("\n\n");
}

// The whole message, as a pure function of the notice and the box.
//
// Separated from sending so the wording - which is the part with the judgement
// in it - is decided somewhere a test can read the answer, rather than only
// inside a mutation whose sole observable is that an email was handed to a queue.
export function ownerNoticeEmail(
	notice: OwnerNotice,
	box: { slug: string; url: string | undefined }
) {
	const link = box.url;
	const reply = `Reply to this email if you need a hand - it reaches ${SUPPORT_EMAIL}.`;

	if (notice.type === "deleted") {
		return {
			subject: `Your Composery box ${box.slug} has been deleted`,
			text: paragraphs([
				`Your box ${box.slug} has been deleted.`,
				deletionReason(notice.trigger),
				"Its files, snapshots and backups went with it. Composery keeps no copy of a deleted box, so this cannot be undone.",
				link ? `Your remaining boxes: ${link}` : undefined,
				reply
			])
		};
	}

	if (notice.type === "suspended") {
		return {
			subject: `Your Composery box ${box.slug} has been suspended`,
			text: paragraphs([
				`Your box ${box.slug} has been suspended and its server powered off.`,
				"Nothing has been deleted. Your files are exactly as you left them and come back with the box.",
				notice.trigger === AUTOMATIC_SUSPENSION
					? notice.reason
					: "A member of Composery staff suspended it.",
				link ? `The box: ${link}` : undefined,
				`Reply to this email to have the suspension reviewed - it reaches ${SUPPORT_EMAIL}.`
			])
		};
	}

	if (notice.type === "unsuspended") {
		return {
			subject: `Your Composery box ${box.slug} is running again`,
			text: paragraphs([
				`The suspension on your box ${box.slug} has been lifted and its server is back on.`,
				link ? `The box: ${link}` : undefined,
				reply
			])
		};
	}

	return {
		subject: `Your Composery box ${box.slug} could not be created`,
		text: paragraphs([
			`We could not finish creating your box ${box.slug}, so there is nothing running yet.`,
			"Composery staff were alerted automatically and are looking at it. You do not need to report it.",
			link ? `The box: ${link}` : undefined,
			reply
		])
	};
}

// Email a box's owner. Never throws.
//
// Every caller is a lifecycle mutation whose real work - the box is deleted, the
// box is suspended - has already happened in the same transaction by the time
// this runs. A notice that failed to send must not turn one of those into a
// failed operation, because a failed operation is what puts a box into a failure
// status and holds its lock. So the whole body is caught, and so is the alert
// that reports the catch: there is nothing behind that alert to rescue it.
export async function sendOwnerEmail(
	ctx: MutationCtx,
	box: Doc<"boxes">,
	notice: OwnerNotice
) {
	try {
		// Silent by configuration, and it says so where someone looks: an owner
		// notice rides the same key and sender domain as the staff alerts whose
		// delivery health `staff/alerts.ts` already reports to the console. A
		// deployment that cannot mail its owners is a deployment already showing an
		// unhealthy alert channel, so this needs no second inert-path signal.
		const from = ownerSender();
		if (!from) return;

		const owner = await findUserByClerkId(ctx, box.user_id);
		// A finished account deletion replaces the address with a `@deleted.invalid`
		// placeholder, and the last box teardown of that same deletion can land
		// after it. Mailing the placeholder would be a guaranteed bounce, and the
		// person it was for asked us to forget them.
		if (!owner || owner.deletion_finished_at) return;

		const { subject, text } = ownerNoticeEmail(notice, {
			slug: box.slug,
			url: optionalWebsiteUrl(boxPath(box._id))
		});

		const emailId = await resendClient().sendEmail(ctx, {
			from,
			to: owner.email,
			subject,
			text,
			// Support is a person reading a mailbox, not a portal, so the reply an
			// owner will send anyway is addressed rather than bounced.
			replyTo: [SUPPORT_EMAIL]
		});

		// Support's answer to "did you tell me?". It is the box's own log rather
		// than a table of its own because that log is already owner-scoped, already
		// shown in the console beside the event being reported, and already carries
		// the retention and purge rules a customer's record needs.
		await appendBoxEvent(ctx, box, "box.owner_emailed", {
			metadata: { notice: notice.type, emailId }
		});
	} catch (error) {
		console.error("Failed to email a box owner", error);
		try {
			const window = Math.floor(Date.now() / OWNER_EMAIL_ALERT_WINDOW_MS);
			await raiseAlert(ctx, {
				key: `owner-email-failed:${window}`,
				severity: "warning",
				subject: "A box owner could not be emailed",
				text: `A ${notice.type} notice for box ${box.slug} (${box._id}) could not be queued.\n\n${
					error instanceof Error ? error.message : String(error)
				}\n\nOwner notices are not retried: the box lifecycle moved on without one, and re-sending later would tell an owner about a state their box has since left. Check the Resend key, the OWNER_EMAIL_FROM sender, and the alert delivery panel in the console - a failure here usually means staff alerts are failing too.`
			});
		} catch {
			// The alert is the fallback and has nothing behind it. It must not be the
			// thing that finally fails the mutation this function promised not to.
		}
	}
}
