// Generates the Composery logo (icon + wordmark) as a self-contained, font-free
// SVG, by outlining "Composery" from Bricolage Grotesque SemiBold to vector
// paths. This is the way logo assets are actually shipped in the wild: no font
// dependency, no @font-face embedding, renders identically everywhere, and
// rasterizes reliably (unlike SVG-with-webfont, which canvas drops in Safari).
//
// The wordmark uses fill="currentColor" so a single lockup adapts to light/dark
// (it follows the text color). The header, the design-page exporter, and the
// code-server overlay all consume this one output, so the lockup's spacing is
// defined here, once. Output: components/logo-data.ts.
//
// The variable woff2 the app ships defaults to weight 800 and fontkit can't read
// its variation deltas, so we outline from the published static 600 instance.
// Run `node scripts/generate-logo.mjs` (or `pnpm logo`).
import { Buffer } from "node:buffer";
import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as fontkit from "fontkit";

const FONT_URL =
	"https://cdn.jsdelivr.net/npm/@fontsource/bricolage-grotesque/files/bricolage-grotesque-latin-600-normal.woff2";
const WORDMARK = "Composery";

// The icon's defs + paths. Keep in sync with components/icon.tsx (ICON_SVG).
const ICON = `<defs><linearGradient gradientUnits="userSpaceOnUse" id="icon-1" x1="128" x2="128" y1="23" y2="233"><stop stop-color="#F6C886"/><stop offset="1" stop-color="#9A5320"/></linearGradient><linearGradient gradientUnits="userSpaceOnUse" id="icon-2" x1="128" x2="128" y1="59" y2="197"><stop stop-color="#ECAE60"/><stop offset="1" stop-color="#8F4C1C"/></linearGradient><linearGradient gradientUnits="userSpaceOnUse" id="icon-3" x1="128" x2="128" y1="90" y2="160"><stop stop-color="#C97E3B"/><stop offset="1" stop-color="#6E3711"/></linearGradient></defs><path d="M200.5 71.4A92 92 0 1 0 200.5 184.6" stroke="url(#icon-1)" stroke-linecap="round" stroke-width="26"/><path d="M154.3 76.3A58 58 0 1 0 184.5 141" stroke="url(#icon-2)" stroke-linecap="round" stroke-width="22"/><path d="M130.4 101.1A27 27 0 1 0 154.1 121" stroke="url(#icon-3)" stroke-linecap="round" stroke-width="17"/>`;

const HEIGHT = 40;
const FONT_SIZE = 22;
// How far the wordmark starts from the left, in viewBox units (icon box is HEIGHT).
const TEXT_X = 40;

const response = await fetch(FONT_URL);
const font = fontkit.create(Buffer.from(await response.arrayBuffer()));
const scale = FONT_SIZE / font.unitsPerEm;
const capPx = (font.capHeight ?? font.ascent * 0.7) * scale;
const baseline = HEIGHT / 2 + capPx / 2; // center the cap height vertically

const iconScale = HEIGHT / 256;
// Icon ink extents in viewBox units. The outer ring (center 128, r 92, stroke
// 26) governs left/top/bottom; its round-capped ends define the right.
const iconLeft = 23 * iconScale;
const iconTop = 23 * iconScale;
const iconRight = 214 * iconScale;
const iconBottom = 233 * iconScale;

const run = font.layout(WORDMARK);
let cursor = 0;
let wmMinX = Infinity;
let wmMaxX = -Infinity;
let wmMinY = Infinity;
let wmMaxY = -Infinity;
const glyphs = run.glyphs
	.map((glyph, index) => {
		const box = glyph.path.bbox;
		wmMinX = Math.min(wmMinX, cursor + box.minX);
		wmMaxX = Math.max(wmMaxX, cursor + box.maxX);
		wmMinY = Math.min(wmMinY, box.minY);
		wmMaxY = Math.max(wmMaxY, box.maxY);
		const path = `<path transform="translate(${cursor} 0)" d="${glyph.path.toSVG()}"/>`;
		cursor += run.positions[index].xAdvance;
		return path;
	})
	.join("");

// Tight bounding box of all the ink (icon + wordmark), then a uniform clear-space
// on every side - so the padding is even (not the lopsided icon-inset vs nothing
// it had before) and no ink sits exactly on the edge, where anti-aliasing clips
// it (the wordmark's trailing "y" especially).
const PAD = 2;
const round = (n) => +n.toFixed(2);
const inkLeft = Math.min(iconLeft, TEXT_X + wmMinX * scale);
const inkTop = Math.min(iconTop, baseline - wmMaxY * scale);
const inkRight = Math.max(iconRight, TEXT_X + wmMaxX * scale);
const inkBottom = Math.max(iconBottom, baseline - wmMinY * scale);
const left = round(inkLeft - PAD);
const top = round(inkTop - PAD);
const width = round(inkRight - inkLeft + 2 * PAD);
const height = round(inkBottom - inkTop + 2 * PAD);
const viewBox = `${left} ${top} ${width} ${height}`;
const inner = `<g transform="scale(${iconScale})">${ICON}</g><g transform="translate(${TEXT_X} ${baseline.toFixed(2)}) scale(${scale.toFixed(5)} ${(-scale).toFixed(5)})" fill="currentColor">${glyphs}</g>`;

const out = join(
	dirname(fileURLToPath(import.meta.url)),
	"..",
	"components",
	"logo-data.ts"
);
await writeFile(
	out,
	`// AUTO-GENERATED by scripts/generate-logo.mjs - do not edit by hand.
// The Composery logo: the icon plus the wordmark outlined from Bricolage Grotesque
// SemiBold, so the asset is self-contained and font-free. The wordmark is
// fill="currentColor", so it follows the text color (dark on light, light on
// dark). Regenerate after the icon or wordmark changes: \`pnpm logo\`.
export const LOGO_INNER = ${JSON.stringify(inner)};
export const LOGO_VIEWBOX = ${JSON.stringify(viewBox)};
export const LOGO_WIDTH = ${width};
export const LOGO_HEIGHT = ${height};
`
);

console.log(
	`Wrote components/logo-data.ts (viewBox "${viewBox}", TEXT_X=${TEXT_X})`
);
